-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibs:: [Integer]
fibs = takeWhile (<4*10^6) xs -- returns the list of fib numbers upto nth term s.t they are less than 4*10^6   
    where xs = 0:scanl (+) 1 xs

solution:: Integer    
solution = sum $ filter even fibs  -- equivalently sum [x | x <- fibs,even x] 
main = putStrLn (show solution)
 
